version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BACKEND_BASE_URL=${REACT_APP_BACKEND_BASE_URL}
    networks:
      - app-network
    volumes:
      - ./resume_templates:/resume_templates

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - BASE_FRONTEND_URL=${BASE_FRONTEND_URL}
      - MONGODB_HOST_STRING=mongodb://db:27017/mydatabase
    networks:
      - app-network
    volumes:
      - ./resume_templates:/resume_templates

  db:
    image: mongo:5.0
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db # Persistent volume for MongoDB data
    networks:
      - app-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run ats
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data: # Named volume for persistent storage

networks:
  app-network:
    driver: bridge
